### PR TITLE
Add Laravel 8 support

### PR DESCRIPTION
**Pull request by patrickomeara**
* cleaned up constraints

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
@juampi92 Could you take a look please?

**Comment by damienorny** [comment]
Hi @juampi92, it would be much appreciated if you could have a look at this PR please 🙏

**Review by juampi92 — APPROVED** [review]

**Comment by juampi92** [comment]
Sorry guys, my GitHub notifications are a mess and I really missed this

**Comment by patrickomeara** [comment]
thanks @juampi92

**Pull request merged**
